### ISSUE TITLE
Log handlers duplicated

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/sdx-sequence#14]
The logger for this service is currently instantiated in the following way if `server.py` is run as a script:

```python
logging.basicConfig(level=settings.LOGGING_LEVEL, format=settings.LOGGING_FORMAT)
handler = logging.StreamHandler(sys.stdout)
app.logger.addHandler(handler)
```
This creates two stream handlers - one to `sys.stdout` (the `handler` object) and the other to `sys.stderr` (default `basicConfig` setup). Is this expected behaviour?

It currently duplicates logs to the console, though I'm not sure if there is any impact elsewhere (such as Splunk).

**Comment by JamesGardiner** [comment]
@tundish can this be closed now the story card is complete?

**Comment by necrophonic** [comment]
Completed
